[package]
name = "tracepoints"
version = "0.1.0"
edition = "2021"
authors = ["Andrea Guarracino <aguarracino@tgen.org>"]
license = "MIT"
description = "Compressed alignment representation"
repository = "https://github.com/AndreaGuarracino/tracepoints"
readme = "README.md"
keywords = ["bioinformatics", "alignment", "compression"]

[dependencies]
#lib_wfa2 = { path = "/home/guarracino/Dropbox/git/lib_wfa2"}
lib_wfa2 = { git = "https://github.com/AndreaGuarracino/lib_wfa2", rev = "fe882ce5f6d4aafc8078a3cdf4b7e69f050b5ef2" }
