[package]
name = "tracepoints"
version = "0.1.0"
edition = "2021"
authors = ["Andrea Guarracino <aguarracino@tgen.org>"]
license = "MIT"
description = "Compressed alignment representation"
repository = "https://github.com/AndreaGuarracino/tracepoints"
readme = "README.md"
keywords = ["bioinformatics", "alignment", "compression"]

[dependencies]
#lib_wfa2 = { path = "/home/guarracino/Dropbox/git/lib_wfa2"}
lib_wfa2 = { git = "https://github.com/AndreaGuarracino/lib_wfa2", rev = "dac5d8b23aeaf4b76bebd5e4e2e1511fc25d18ac"}

[dev-dependencies]
# Used by es2bit_bench to measure gzip-compressed byte sizes.
flate2 = "1"
